# Generated by Django 5.1.6 on 2025-06-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-13 15:00'),
            preserve_default=False,
        ),
    ]
